include_version = true
braces = "SameLine"
line_length = 100
tab_width = 2
language = "C"

[export]
prefix = "zsplg_"

[parse]
parse_deps = true
include = ["zsplg-core"]

[fn]

[struct]
derive_eq = true

[enum]
prefix_with_name = true
derive_helper_methods = true

[macro_expansion]

[defines]
